version: "3"
services:
  #mssql docker

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
    networks:
      - travelonet2023

  travelo-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=myPassword1]
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - travelonet2023

  mailing-service:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.mailservice
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=mypass
      - RABBITMQ_VIRTUALHOST=/
      - OUTLOOK_MAIL=travelo-reservations@outlook.com
      - OUTLOOK_PASS=Travelo-pass123
    depends_on:
      - rabbitmq
      - travelo-sql
      - travelo-api
    networks:
      - travelonet2023
    ports:
      - 7101:80

  travelo-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:Mac=Server=travelo-sql,1433;Database=210333;User Id=sa;Password=myPassword1];Encrypt=false;
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=mypass
      - RABBITMQ_VIRTUALHOST=/
    ports:
      - 7100:7100
    networks:
      - travelonet2023
    links:
      - travelo-sql
    depends_on:
      - travelo-sql
      - rabbitmq

networks:
  travelonet2023:
    driver: bridge
